services:
  server:
    hostname: "abz"
    image: "openjdk:19-jdk-alpine"
    working_dir: "/app"
    volumes:
      - "../../server/target:/app"
    environment:
      MODE: "development"
      VIRTUAL_HOST: "api.${ABZ_URL}"
      VIRTUAL_PORT: "8585"
    ports:
      - "8585:8585"
    command: ["java", "-jar", "server-0.0.1-SNAPSHOT.jar"]
